// Code generated by go-swagger; DO NOT EDIT.

package questions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"NOOBDY/questions_server/sdk/models"
)

// ListQuestionsReader is a Reader for the ListQuestions structure.
type ListQuestionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListQuestionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListQuestionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListQuestionsOK creates a ListQuestionsOK with default headers values
func NewListQuestionsOK() *ListQuestionsOK {
	return &ListQuestionsOK{}
}

/*ListQuestionsOK handles this case with default header values.

A list of questions
*/
type ListQuestionsOK struct {
	Payload []*models.Question
}

func (o *ListQuestionsOK) Error() string {
	return fmt.Sprintf("[GET /questions][%d] listQuestionsOK  %+v", 200, o.Payload)
}

func (o *ListQuestionsOK) GetPayload() []*models.Question {
	return o.Payload
}

func (o *ListQuestionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
