// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Question Question defines the structure for an API question
//
// swagger:model Question
type Question struct {

	// answer
	Answer string `json:"answer,omitempty"`

	// option a
	OptionA string `json:"option_a,omitempty"`

	// option b
	OptionB string `json:"option_b,omitempty"`

	// option c
	OptionC string `json:"option_c,omitempty"`

	// option d
	OptionD string `json:"option_d,omitempty"`

	// question
	Question string `json:"question,omitempty"`
}

// Validate validates this question
func (m *Question) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Question) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Question) UnmarshalBinary(b []byte) error {
	var res Question
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
