// Code generated by go-swagger; DO NOT EDIT.

package questions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListQuestionParams creates a new ListQuestionParams object
// with the default values initialized.
func NewListQuestionParams() *ListQuestionParams {
	var ()
	return &ListQuestionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListQuestionParamsWithTimeout creates a new ListQuestionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListQuestionParamsWithTimeout(timeout time.Duration) *ListQuestionParams {
	var ()
	return &ListQuestionParams{

		timeout: timeout,
	}
}

// NewListQuestionParamsWithContext creates a new ListQuestionParams object
// with the default values initialized, and the ability to set a context for a request
func NewListQuestionParamsWithContext(ctx context.Context) *ListQuestionParams {
	var ()
	return &ListQuestionParams{

		Context: ctx,
	}
}

// NewListQuestionParamsWithHTTPClient creates a new ListQuestionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListQuestionParamsWithHTTPClient(client *http.Client) *ListQuestionParams {
	var ()
	return &ListQuestionParams{
		HTTPClient: client,
	}
}

/*ListQuestionParams contains all the parameters to send to the API endpoint
for the list question operation typically these are written to a http.Request
*/
type ListQuestionParams struct {

	/*ID
	  The id of the product for which the operation relates

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list question params
func (o *ListQuestionParams) WithTimeout(timeout time.Duration) *ListQuestionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list question params
func (o *ListQuestionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list question params
func (o *ListQuestionParams) WithContext(ctx context.Context) *ListQuestionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list question params
func (o *ListQuestionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list question params
func (o *ListQuestionParams) WithHTTPClient(client *http.Client) *ListQuestionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list question params
func (o *ListQuestionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list question params
func (o *ListQuestionParams) WithID(id int64) *ListQuestionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list question params
func (o *ListQuestionParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListQuestionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
