// Code generated by go-swagger; DO NOT EDIT.

package questions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new questions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for questions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ListQuestion(params *ListQuestionParams) (*ListQuestionOK, error)

	ListQuestions(params *ListQuestionsParams) (*ListQuestionsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ListQuestion Returns a single question from the database
*/
func (a *Client) ListQuestion(params *ListQuestionParams) (*ListQuestionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListQuestionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listQuestion",
		Method:             "GET",
		PathPattern:        "/questions/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListQuestionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListQuestionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listQuestion: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListQuestions Returns a list of questions from the database
*/
func (a *Client) ListQuestions(params *ListQuestionsParams) (*ListQuestionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListQuestionsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listQuestions",
		Method:             "GET",
		PathPattern:        "/questions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListQuestionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListQuestionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listQuestions: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
